# These are supported funding model platforms

github: [bayudwiyansatria]
patreon: bayudwiyansatria
open_collective: bayudwiyansatria
ko_fi: bayudwiyansatria
custom: # Replace with a single custom sponsorship URL
