name: User Action

on:
  push:
    branches:
      - users/*
jobs:
  build:
    name: Main
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          java-version: [1.8]
          os: [ubuntu-latest]
    steps:
      - name: Prepare
        uses: actions/checkout@v1
      - name: Set Up Java Development Kit
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}